name: chrisbran
favicon: null
layout_spectrum: 0.49255
typography_spectrum: 0.4996
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.8593127538915724
  saturation: 0.988733425969258
  rhythmicContrast: 0.18876085337251425
purpose: []
